module.exports = {
  BOT_NAME     : 'Devmux',
  VERSION      : '2.0.0',
  CREDIT       : 'm3oza',
  STATUS       : '.gg/m3oza',
  SUPPORT_URL  : 'https://discord.gg/m3oza',
  EMBED_FOOTER : '⚡ Devmux  •  .gg/m3oza  •  by m3oza',
  PREFIX       : process.env.PREFIX || '$',
  COOLDOWN_DEFAULT : 3,

  // Emoji set
  E: {
    CHECK   : '✅',
    CROSS   : '❌',
    WARN    : '⚠️',
    INFO    : 'ℹ️',
    MUSIC   : '🎵',
    TICKET  : '🎫',
    GEAR    : '⚙️',
    SHIELD  : '🛡️',
    CROWN   : '👑',
    BOLT    : '⚡',
    WAVE    : '👋',
    PARTY   : '🎉',
    MIC     : '🎙️',
    LIST    : '📋',
    LOCK    : '🔒',
    UNLOCK  : '🔓',
    HAMMER  : '🔨',
    MUTE    : '🔇',
    VOL     : '🔊',
    SKIP    : '⏭️',
    STOP    : '⏹️',
    PAUSE   : '⏸️',
    PLAY    : '▶️',
    LOOP    : '🔁',
    QUEUE   : '🗒️',
    SHUFFLE : '🔀',
    LOADING : '⏳',
    STAR    : '⭐',
  },
};
